### PR TITLE
Hello World written in html

### PR DESCRIPTION
**Pull request by DewashishCodes**

### CODE REVIEW

**Comment by abhisek247767** [comment]
please remove C code ..someone already contribute it.

**Comment by DewashishCodes** [comment]
> please remove C code ..someone already contribute it.

I have removed it, please Merge

**Comment by abhisek247767** [comment]
Done. Please star the repo and follow me in GitHub :)

**Comment by DewashishCodes** [comment]
Hey , My PR was flagged as spam although I don't find anything close to spam or malicious in my PR. If it is something which happened by accident from your side please rectify it as it puts my hacktober progress at risk. Thanks

**Comment by abhisek247767** [comment]
It's fine..Previosly I do as Spam.. because you not follow guidelines

**Pull request merged**
