### PR TITLE
Added hello_world in ruby

### PR DESCRIPTION
**Pull request by aaryak1369**

### CODE REVIEW

**Comment by aaryak1369** [comment]
@abhisek247767 i dont understand why this pull request is flagged as spam. i only added hello_world file in ruby.

**Comment by abhisek247767** [comment]
ruby code already available

**Comment by aaryak1369** [comment]
I don't see it.
These files are visible to me and I donit see .rb file anywhere.

please don't mark my pr as spam without double checking as it will permanently disqualify me from hacktoberfest and this is my first hacktoberfest.

**Comment by abhisek247767** [comment]
it's conflicting in Readme.md file. can you delete readme file and again raise PR. I will merge it..

**Comment by aaryak1369** [comment]
okay, thanks

**Pull request closed without merging**
