### PR TITLE
Update hello_world.py

### PR DESCRIPTION
**Pull request by utkarsh2004git**

### CODE REVIEW

**Comment by utkarsh2004git** [comment]
Please merge pull request

**Comment by abhisek247767** [comment]
already availbe.first check then do pr.

**Comment by utkarsh2004git** [comment]
okay so it was reason for spamming??you dont have mind.

**Comment by abhisek247767** [comment]
yes.

**Comment by utkarsh2004git** [comment]
You should give warning first not marked as spam.

**Comment by abhisek247767** [comment]
this is learning. before do Pr think twice at least

**Comment by utkarsh2004git** [comment]
Because of you I am disqualified from hacktoberfest.

**Comment by utkarsh2004git** [comment]
Can you remove spam tag?

**Pull request closed without merging**
