### PR TITLE
Added code in C, C++, Java and Ruby

### PR DESCRIPTION
**Pull request by Rasesh-Srivastava**
Contributing to Issue #2. Please merge the PR. Thanks.

### CODE REVIEW

**Comment by abhisek247767** [comment]
please check the guideline first Star the repo and then follow me :)

**Comment by Rasesh-Srivastava** [comment]
Done, now can you merge the PR?

**Comment by Rasesh-Srivastava** [comment]
> please check the guideline first Star the repo and then follow me :)

Starred the repo and followed you.

**Comment by abhisek247767** [comment]
please check whatever code you want to push that already present...

**Pull request closed without merging**
